Basic profile page logic done
dcsil/Lampsz-App pull request #47
Opened 2022-11-30 21:15 UTC by matticyang

2022-11-30 21:37 UTC, matticyang reviewed
need u guys to check my migrations

2022-11-30 21:40 UTC, matticyang reviewed
migration seems to be failing, fixing this

2022-11-30 23:40 UTC, larryworm1127 requested changes

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/actions/profile.ts
> +  .get('/api/profile/'+userId)
let's reformat this file

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Profile/BusinessProfile.tsx
> +      <div style={styles.infoContainer}>
Is there any reason why we switched from container to div?

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Profile/InfluencerProfile.tsx
> +      <div style={styles.contentContainer}>
Is this where the influencer demo content gonna go?

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Profile/BusinessProfile.tsx
> +export default function BusinessProfile ({company}: any): JSX.Element {
I would prefer not to use `any` type. If you don't want to create an interface, then you can simply do something like:
```
export default function BusinessProfile ({ company }: { company: type }): JSX.Element {
```

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Profile/index.tsx
> +  var dict = {username: "", userType: 0}
I'm assuming there's going to be more fields in this object? Since I see in `BusinessProfile` and `InfluencerProfile` that there's reference to fields that don't exist here

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Profile/index.tsx
> +    return <></>
This is probably gonna cause compilation error for webpack and break production, either remove it or change it like `<div>` or something

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Routes.tsx
> +      <NavWrapper>
We want `<RequireAuth>` for this one too, since only user who are logged in can see the profiles.

2022-11-30 23:40 UTC, larryworm1127 commented on client/src/components/Routes.tsx
>      path: '/profile',
This one can be removed since you added a new path above it

2022-11-30 23:40 UTC, larryworm1127 commented on lampsz/apis/models.py
> +    tiktokUsername = models.CharField(null=False, blank=False, max_length=20)
This should be channel name right? Since we are dealing with Youtuber here.

2022-11-30 23:40 UTC, larryworm1127 commented on lampsz/apis/urls.py
> +        "influencerProfile/<str:influencer_username>", profile.public_influencer_detail
What's the difference between `public_influencer_detail` and `influencer_detail_view`? Also for URL, I think a better way is to split the words. So instead of `influencerProfile/<str:influencer_username>`, `profile/influencer/<str:influencer_username>` is nicer.

2022-11-30 23:40 UTC, larryworm1127 commented on package.json
> -    "dev": "webpack --mode development --watch",
Why remove the watch?

2022-11-30 23:40 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +        user = models.User.objects.get(id=user_id)
User model has an `is_influencer` field which you can use to determine whether to search in influencer or company model.

2022-11-30 23:40 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +        if len(influencers) > 0:
Django's `queryset` has an `.exists()` method that's handy for this.

2022-11-30 23:40 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +            influencer = influencers[0]
Prefer `influencer.first()` instead of straight indexing

2022-11-30 23:47 UTC, matticyang commented on package.json
> -    "dev": "webpack --mode development --watch",
yeh i can remove this

2022-12-01 00:35 UTC, larryworm1127 requested changes

2022-12-01 00:35 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +            influencers = models.Influencer.objects.filter(user=user)
why not chain this together?
```
influencer = models.Influencer.objects.filter(user=user).first()
```

2022-12-01 00:35 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +            userType = utils.UserType.INFLUENCER
User model actually has a method called `get_user_type()` that gives you the UserType directly so you don't have to assign it to variable here

2022-12-01 00:45 UTC, larryworm1127 approved these changes

2022-12-01 00:55 UTC, merged