Create marketing task with image
dcsil/Lampsz-App pull request #55
Opened 2022-12-02 19:10 UTC by zekai128

Add create task capability to the My Marketing Tasks page for businesses.

Create task UI created with Dialog box. 

When a new task is created, a callback automatically refreshes the list of tasks so that My marketing Tasks updates with the newly created task without a manual refresh of the page.

2022-12-02 19:31 UTC, larryworm1127 requested changes

2022-12-02 19:31 UTC, larryworm1127 commented on client/src/components/MyMarketingTasks/index.tsx
> +    axios.post('http://127.0.0.1:8000/api/create_task/', uploadData, {
Don't include domain in the URL, it will fail in production.

2022-12-02 19:31 UTC, larryworm1127 commented on client/src/components/MyMarketingTasks/index.tsx
> +    axios.post('http://127.0.0.1:8000/api/get_company_tasks/', {"userId": auth.userId}, {
Same here. Also, let's move the axios calls into a new file in `actions` folder.

2022-12-02 19:31 UTC, larryworm1127 commented on lampsz/settings/base.py
> +MEDIA_ROOT = os.path.join(BASE_DIR, "media")
we already have pathlib imported, which is the recommended way of dealing with file paths since Python 3.9. So you can actually just do `BASE_DIR / "media"`.

2022-12-02 19:31 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +    data = serialize(
Why use django's serailize when we already created a `MarketingTaskSerializer`?

2022-12-02 19:31 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +    userId = request.data["userId"]
Use rest_framework's serializer to create the object instead of extracting them one by one. Also, since it's a plain create and a very simple filter, you can combine the create and get views using rest framework's `ListCreateAPIView`, and define your own queryset. Refer to these docs:
- https://www.django-rest-framework.org/api-guide/generic-views/
- https://www.django-rest-framework.org/api-guide/filtering/

2022-12-02 19:31 UTC, larryworm1127 commented on lampsz/apis/urls.py
>      path("create_task/", profile.create_marketing_task),
url usually shouldn't contain action as that is determined by the method used (GET, POST, etc.), so something like `"tasks/"` as url should suffice here

2022-12-02 19:44 UTC, larryworm1127 commented
Also, `package-lock.json` is gone again lol

2022-12-03 02:48 UTC, zekai128 commented on lampsz/apis/views/profile.py
> +    data = serialize(
Removed this method, using the new generic method for Marketing Task instead.

2022-12-03 03:33 UTC, zekai128 commented on client/src/components/MyMarketingTasks/index.tsx
> +    axios.post('http://127.0.0.1:8000/api/get_company_tasks/', {"userId": auth.userId}, {
will factor these out when I write the calls for searching marketing tasks. It's not clear at this point which lines of code are going to get factored out.

2022-12-03 04:39 UTC, larryworm1127 requested changes

2022-12-03 04:39 UTC, larryworm1127 commented on lampsz/apis/views/profile.py
> +    return HttpResponse({"message": "successful"}, status=200)
Use rest_framework's `Response` instead of `HttpResponse`

2022-12-03 04:39 UTC, larryworm1127 commented on client/src/actions/tasks.ts
> +    axios.get(('/api/tasks?' + 'user_id=' + userId), {
Instead of using `+`, use
```
`/api/tasks?user_id=${userId}`
```

2022-12-03 05:41 UTC, larryworm1127 approved these changes

2022-12-03 05:47 UTC, merged